version: "2"

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gofmt
    - misspell
    - unconvert
    - unparam

  settings:
    gofmt:
      simplify: true

issues:
  exclusions:
    rules:
      - path: _test\.go
        linters:
          - errcheck
          - unparam
